version: '3.8'
services:
    db:
      container_name: postgres
      image: postgres:latest
      restart: on-failure
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      networks:
      - home
    backend:
      container_name: backend-nest
      build: 
        context: ./
      depends_on:
        - db
      restart: on-failure
      ports:
        - 4001:4001
      environment:
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      networks:
      - home

networks:
  home: